import type { Metadata, Viewport } from "next";
import { Inter, JetBrains_Mono } from "next/font/google";
import "./globals.css";

/* ─── Fonts ──────────────────────────────────────────────────────────────── */

const inter = Inter({
  variable: "--font-inter",
  subsets:  ["latin"],
  display:  "swap",
  weight:   ["300", "400", "500", "600", "700", "800"],
  preload:  true,
});

const jetbrainsMono = JetBrains_Mono({
  variable: "--font-jetbrains-mono",
  subsets:  ["latin"],
  display:  "swap",
  weight:   ["400", "600", "700", "800"],
  preload:  true,
});

/* ─── Viewport ───────────────────────────────────────────────────────────── */

export const viewport: Viewport = {
  themeColor:    "#0a0a0f",
  width:         "device-width",
  initialScale:  1,
  // Prevents iOS auto-zoom on input focus (UX / CLS fix)
  maximumScale:  5,
  colorScheme:   "dark",
};

/* ─── Metadata ───────────────────────────────────────────────────────────── */

const SITE_URL  = "https://your-domain.com";
const SITE_NAME = "AI Automation Platform";
const TITLE     = "AI Automation Platform – Automate Everything";
const DESC      =
  "The most powerful AI automation platform. Build, deploy, and scale intelligent workflows in minutes. 500+ integrations, 99.98% uptime, sub-10ms latency.";

export const metadata: Metadata = {
  // All relative URLs in metadata resolve against this base
  metadataBase: new URL(SITE_URL),

  /* ── Title ── */
  title: {
    default:  TITLE,
    template: `%s | ${SITE_NAME}`,
  },

  /* ── Description / Keywords ── */
  description: DESC,
  keywords: [
    "AI automation",
    "workflow automation",
    "artificial intelligence",
    "machine learning platform",
    "SaaS automation",
    "no-code AI",
    "AI agents",
    "workflow orchestration",
    "enterprise automation",
  ],

  /* ── Authorship ── */
  authors:  [{ name: SITE_NAME, url: SITE_URL }],
  creator:  SITE_NAME,
  publisher: SITE_NAME,

  /* ── Canonical ── */
  alternates: {
    canonical: SITE_URL,
    languages: {
      "en-US": SITE_URL,
    },
  },

  /* ── Open Graph ── */
  openGraph: {
    type:        "website",
    locale:      "en_US",
    url:         SITE_URL,
    siteName:    SITE_NAME,
    title:       TITLE,
    description: DESC,
    // Next.js resolves /opengraph-image.png from app/opengraph-image.tsx
    images: [
      {
        url:    "/opengraph-image.png",
        width:  1200,
        height: 630,
        alt:    `${SITE_NAME} — Automate Everything, Scale Infinitely`,
        type:   "image/png",
      },
    ],
  },

  /* ── Twitter / X ── */
  twitter: {
    card:        "summary_large_image",
    site:        "@yourtwitterhandle",
    creator:     "@yourtwitterhandle",
    title:       TITLE,
    description: DESC,
    images: [
      {
        url: "/opengraph-image.png",
        alt: `${SITE_NAME} — Automate Everything, Scale Infinitely`,
      },
    ],
  },

  /* ── Icons (all generated by app/icon.tsx & app/apple-icon.tsx) ── */
  icons: {
    icon: [
      { url: "/icon.png",         type: "image/png", sizes: "32x32"  },
      { url: "/icon.png",         type: "image/png", sizes: "16x16"  },
    ],
    apple:   [{ url: "/apple-icon.png", sizes: "180x180", type: "image/png" }],
    shortcut: "/icon.png",
  },

  /* ── Web App Manifest ── */
  manifest: "/site.webmanifest",

  /* ── Robots ── */
  robots: {
    index:  true,
    follow: true,
    googleBot: {
      index:               true,
      follow:              true,
      "max-video-preview": -1,
      "max-image-preview": "large",
      "max-snippet":       -1,
    },
  },

  /* ── Verification (add when deploying) ── */
  // verification: {
  //   google:  "your-google-search-console-token",
  //   yandex:  "your-yandex-token",
  // },

  /* ── Category ── */
  category: "technology",
};

/* ─── Root Layout ────────────────────────────────────────────────────────── */

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html
      lang="en"
      dir="ltr"
      className={`${inter.variable} ${jetbrainsMono.variable} h-full antialiased`}
    >
      <head>
        {/*
          DNS prefetch for external origins used at render time.
          next/font/google is self-hosted after build, so no Google Fonts
          origin is needed. Add any third-party domains here.
        */}
        <link rel="dns-prefetch" href="//your-domain.com" />

        {/* Structured data — Organization */}
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{
            __html: JSON.stringify({
              "@context":   "https://schema.org",
              "@type":      "SoftwareApplication",
              name:         SITE_NAME,
              url:          SITE_URL,
              description:  DESC,
              applicationCategory: "BusinessApplication",
              operatingSystem: "Web",
              offers: {
                "@type":    "AggregateOffer",
                priceCurrency: "USD",
                lowPrice:   "0",
                highPrice:  "99",
                offerCount: "3",
              },
              aggregateRating: {
                "@type":       "AggregateRating",
                ratingValue:   "4.9",
                ratingCount:   "1200",
                bestRating:    "5",
                worstRating:   "1",
              },
            }),
          }}
        />
      </head>
      <body className="min-h-full flex flex-col">
        {/*
          Skip-to-content link — renders off-screen, jumps into view on Tab.
          Required for keyboard accessibility (WCAG 2.4.1).
        */}
        <a
          href="#main-content"
          className="skip-to-content"
          aria-label="Skip to main content"
        >
          Skip to content
        </a>

        {children}
      </body>
    </html>
  );
}
